### ISSUE TITLE
Missing audio file of how Shlomi says ccql

### ISSUE THREAD

**Issue by michaelcoburn** [github/ccql#29]
"Hello, this is Shlomi Noach, and I pronounce ccql as ccql."  Linus will be so proud of you.

http://www.paul.sladen.org/pronunciation/torvalds-says-linux.mp3

**Comment by shlomi-noach** [comment]
An oversight. Meanwhile this is how you would pronounce it with Italian accent: https://translate.google.com/#it/en/Si%20Sequel
Please make sure to roll the tongue gently at the final "l".

**Comment by michaelcoburn** [comment]
Having given this further thought, I would instead prefer that at Percona Live 2016, Shlomi and team lead a Tutorial on how to pronounce it correctly in multiple languages.  Doing so at the Hyatt bar is likely a suitable venue.

Closing as "Won't Fix until April 18, 2016"

See you guys then!!
