### ISSUE TITLE
host section should take a default database/schema as well as host and ip

### ISSUE THREAD

**Issue by wederbrand** [github/ccql#30]
Sometimes it's neat to be able to query lots of databases using a default schema and be able to leave out the schema name in the query. 

Several hosts might have the same tables but different schemas, typically in a sharded environment.

Thanks.

**Comment by shlomi-noach** [comment]
Whoops sorry, notification settings were not set properly. 

Default schema is already supperted in [1.1.4](https://github.com/github/ccql/releases/tag/v1.1.4)

Usage: `-d schema_name`
