### ISSUE TITLE
Add ability to read credentials from MySQL options file

### ISSUE THREAD

**Issue by datacharmer** [github/ccql#31]
The options file for ccql is simply:

    [client]
    user=xxxx
    password=yyyy

If the file passed to ccql with -C contains only this information, it is recognized and used.
However, the same information may be already available in MySQL options file `/etc/my.cnf` or `$HOME/.my.cnf`.
The only problem is that the MySQL options file may contain more information than what ccql is looking for. It will fail when reading the `[mysql]` scope, or when the `[client]` scope contains unexpected fields (such as `socket` or `port`).

Possible solutions:

* Allow ccql to skip unnecessary information and only read the known options from the scope it recognizes.
* Instruct ccql to recognize a `[ccql]` scope in MySQL options file, similar to what other clients do.

**Comment by shlomi-noach** [comment]
Whoops sorry, notification settings were not set properly. This issue is now assigned.

**Comment by shlomi-noach** [comment]
Closed by #33
